# Generated by Django 5.1.5 on 2025-01-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlElectorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ci',
            field=models.IntegerField(unique=True),
        ),
    ]
