# Generated by Django 5.1.5 on 2025-01-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlElectorApp', '0002_alter_profile_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
