# Generated by Django 5.1.5 on 2025-02-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlElectorApp', '0003_profile_image_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
    ]
